spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jjowin
    username: root
    password: 12340119
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  servlet:
    session:
      timeout: 3600 # 세션 만료시간 1시간
