spring:
  datasource:
    url: jdbc:mariadb://43.200.200.255:3306/jjowin
    username: root
    password: 12340119
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
